title:            PHP Way
tagline:          Meetup PHP en la Ciudad de México.
description:      Describe your website.
canonical: http://phpway.mx

# Owner/author information
owner:
  name:           PHP Way
  avatar:         avatar.png
  bio:            "Meetup PHP The Right Way Mexico"
  email:          hey@phpway.mx
  twitter:        phpwaymx
  github:         phpwamx
  disqus:         phpwaymx
  location:       "Mexico DF"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Meetup
    url: https://www.meetup.com/PHP-The-Right-Way
    external: true
  - title: Github
    url: https://github.com/phpwaymx
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Mexico_City
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
